input {
  http {
    host => "0.0.0.0"
    port => 8080
    codec => json
  }
}

filter {
  if ![host][ip] {
    mutate {
      add_field => { "[host][ip]" => "%{[headers][http_host]}" }
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
